### ISSUE TITLE
Add @sn3p's refurbished dev blogs 

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/website#1429]
- [x] Flexible cover images using intrinsic ratio #1489 merged
- [x] Color placeholders for loading images #1459 
- [ ] Customizing the Intercom Launcher #1526

This is still up

https://www.defacto.nl/blog/animated-loading-indicator-with-isometric-cubes/
